 # test_secrets.py - FOR EDUCATIONAL PURPOSES ONLY                                                                                                                                                                                                                                     
  # These are fake values that match secret patterns                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                        
  # AWS Access Key (AKIA + 16 alphanumeric)                                                                                                                                                                                                                                             
  AWS_ACCESS_KEY = "AKIAIOSFODNN7EXAMPLE"                                                                                                                                                                                                                                               
  AWS_SECRET_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                        
  # GitHub Personal Access Token (classic - 40 chars after ghp_)                                                                                                                                                                                                                        
  GITHUB_TOKEN = "ghp_aBcDeFgHiJkLmNoPqRsTuVwXyZ1234567890"                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                        
  # GitHub Personal Access Token (fine-grained)                                                                                                                                                                                                                                         
  GITHUB_FG_TOKEN = "github_pat_11ABCDEFG0123456789012_aBcDeFgHiJkLmNoPqRsTuVwXyZ1234567890abcdefghijk"                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                        
  # Slack Bot Token                                                                                                                                                                                                                                                                     
  SLACK_BOT_TOKEN = "xoxb-123456789012-9876543210987-AbCdEfGhIjKlMnOpQrStUvWx"                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                        
  # Slack Webhook                                                                                                                                                                                                                                                                       
  SLACK_WEBHOOK = "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX"                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                        
  # Stripe Secret Key (live)                                                                                                                                                                                                                                                            
  STRIPE_SECRET_KEY = "sk_live_51HxRABCDEFGhIjKlMnOpQrS0tUvWxYz1234567890AbCdEfGhI"                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                        
  # SendGrid API Key                                                                                                                                                                                                                                                                    
  SENDGRID_API_KEY = "SG.abcdefghijklmnop.qrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ12"                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                        
  # NPM Access Token                                                                                                                                                                                                                                                                    
  NPM_TOKEN = "npm_aBcDeFgHiJkLmNoPqRsTuVwXyZ1234567890"                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                        
  # OpenAI API Key                                                                                                                                                                                                                                                                      
  OPENAI_API_KEY = "sk-proj-abcdefghijklmnopqrstuvwxyz1234567890ABCD"                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                        
  # Google API Key                                                                                                                                                                                                                                                                      
  GOOGLE_API_KEY = "AIzaSyAbCdEfGhIjKlMnOpQrStUvWxYz12345678"                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                        
  # Private RSA Key                                                                                                                                                                                                                                                                     
  PRIVATE_KEY = """-----BEGIN RSA PRIVATE KEY-----                                                                                                                                                                                                                                      
  MIIEpAIBAAKCAQEA2Z3qX2BTLS4e3Iw4cXctK1234567890abcdefghijklmnopqr                                                                                                                                                                                                                     
  stuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890abcdefghijklmnopqrst                                                                                                                                                                                                                      
  uvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890abcdefghijklmnopqrstuv                                                                                                                                                                                                                      
  -----END RSA PRIVATE KEY-----"""                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                        
  # Database connection string                                                                                                                                                                                                                                                          
  DATABASE_URL = "postgresql://admin:SuperSecretP@ssw0rd123@db.example.com:5432/production"
